const mongoose = require('mongoose');
const Schema = mongoose.Schema;

const SeriesSchema = new Schema({
    title : {
        type : String,
        required : true,
    },
    creation : {
        type : Number,
        required : true,
        default : 2000
    },
    image : {
        type : String,
        required : false,
        default : '#'
    },
    visible : {
        type : Date,
        required : true
    },
    seasons : {
        type : Number,
        required : true,
        default : 1
    },
    tags : {
        type : Array,
        required: false,
        default: []
    }
    /*
    * +créé par
    * +historique des mises à jour et par qui
    * +le réalisateur
    * +les acteurs
    * +trailer url
    * +un synopsis
    * +plateforms
    * +rating
    * +tag suggestion
    * +autogenerated form from this file
    */
})

const Series = mongoose.model('Series', SeriesSchema)

module.exports = Series
